variables:
  GIT_SUBMODULE_STRATEGY: recursive
  RISCV: '$CI_PROJECT_DIR/install'

before_script:
  - mkdir -p $RISCV

after_script:
  - chmod -R u+w $RISCV

all:
  script:
    ### build_install_gcc
    - make tc-pulp tc-ariane-linux
    ### build_install_pulp-sdk
    - make pulp-sdk
    ### build_install_hero-sdk
    - export PULP_RISCV_GCC_TOOLCHAIN=$RISCV
    - source pulp/sdk/sourceme.sh
    - make hero-sdk
    ### build_install_llvm
    - make hero-llvm
    ### build_examples
    - source env/urania.sh
    - make -C openmp-examples/helloworld all
    ### compile_testbench
    - cd hardware/vsim
    - ./compile.sh
    - cd -
    ### simulate_examples
    - source env/sim.sh
    - make -C openmp-examples/helloworld only=pulp clean all
    - cd hardware
    - test/gen_slm_files.sh helloworld
    - cd vsim
    - ./start_sim.sh
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
