variables:
  GIT_SUBMODULE_STRATEGY: recursive
  RISCV: '$CI_PROJECT_DIR/install'

before_script:
  - mkdir -p $RISCV

after_script:
  - chmod -R u+w $RISCV

all:
  script:
    ### build_install_gcc
    - make tc-pulp tc-ariane-linux
    ### build_install_pulp-sdk
    - make pulp-sdk
    ### build_install_hero-sdk
    - export PULP_RISCV_GCC_TOOLCHAIN=$RISCV
    - source pulp/sdk/sourceme.sh
    - make hero-sdk
    ### build_install_llvm
    - make hero-llvm
    ### build_examples
    - source env/urania.sh
    - >
      for d in helloworld; do
        make -C openmp-examples/$d all
      done
    ### compile_testbench
    - cd hardware/vsim
    - ./compile.sh
    - cd -
    ### simulate_examples
    - source env/sim.sh
    - >
      for d in tests-pulp helloworld; do
        make -C openmp-examples/$d only=pulp clean all
        cd hardware/vsim
        ../test/gen_slm_files.sh $d
        ./start_sim.sh
      done
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
