variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'
  RUST_LOG: 'memora=debug'
  PATH: '/home/gitlabci/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/condor/bin:/usr/sepp/bin'
  TEMP_JOB_DIR: '$CI_PROJECT_DIR/archive/hero_gitlab_ci_$CI_JOB_ID'

before_script:
  - env
  - mkdir -p $HERO_INSTALL
  - mkdir -p "$TEMP_JOB_DIR"

after_script:
  - chmod -R u+w $HERO_INSTALL
  - chmod -R u+w "$TEMP_JOB_DIR"
  - rm -rf "$TEMP_JOB_DIR"

stages:
  - build_test_archive

build_test_archive:
  stage: build_test_archive
  script:
    - ./pack_siemens.sh
    - cd "$TEMP_JOB_DIR"
    - cp "$CI_PROJECT_DIR/hero_siemens.tar.gz" .
    # Extract archive and run setup.
    - tar xf hero_siemens.tar.gz && rm hero_siemens.tar.gz
    - |
      export CMUX_ROOT="$(pwd)/cmux"
      export HERO_INSTALL="$(pwd)/install"
      mkdir -p "$HERO_INSTALL"
      ./setup.sh
    # Build `baby_gemm` and `darknet` with PREM enabled.
    - |
      export CMUX_ROOT="$(pwd)/cmux"
      export HERO_INSTALL="$(pwd)/install"
      cd openmp-examples/baby_gemm
      ./compile
      cd ../darknet
      ./compile
    # Append binaries built during CI run.
    - $CI_PROJECT_DIR/pack_siemens_append.sh $CI_PROJECT_DIR/hero_siemens.tar.gz
  artifacts:
    paths:
      - hero_siemens.tar.gz
