variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'

before_script:
  - mkdir -p $HERO_INSTALL

after_script:
  - chmod -R u+w $HERO_INSTALL

stages:
  - build_fpga
  - build_test_rest

build_fpga:
  stage: build_fpga
  rules:
    - changes:
      - hardware/deps/**/*
      - hardware/fpga/**/*
      - hardware/src/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
      when: always
    - if: $CI_EVERYTHING
      when: always
  script: make -C hardware/fpga all

build_test_rest:
  stage: build_test_rest
  script:
    ### build base toolchains
    - make tc-pulp tc-hrv-olinux tc-har-olinux
    ### build accelerator sdk
    - make sdk-pulp
    ### build host sdks
    - make sdk-har
    - make sdk-hrv
    ### build other images
    - make br-hrv-ediggenesys2
    - make br-har-exilzcu102
    - make br-hrv-eqemu
    ### build llvm
    - make tc-llvm
    ### build tools
    - make tools-hrv-openocd
    ### build examples
    - source env/esim.sh
    - >
      for d in helloworld; do
        make -C openmp-examples/$d all
      done
    ### compile testbench
    - cd hardware/vsim
    - ./compile.sh
    - cd -
    ### simulate examples
    - cd hardware/vsim
    - >
      for d in tests-pulp helloworld; do
        make -C ../../openmp-examples/$d only=pulp clean all
        ../test/gen_slm_files.sh $d
        ./start_sim.sh
      done
    - cd -
    ### test benchmarks
    - >
      for d in openmp-examples/polybench-acc/*/; do
        if [ $(basename $d) = "common" ]; then
          continue
        fi
        make -C $d only=pulp default-as=host clean all
        make -C $d only=pulp clean all
        .gitlab-ci.d/verify-bench.sh $(basename $d)
      done
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
