variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'
  TEMP_JOB_DIR: '/tmp/hero_gitlab_ci_$CI_JOB_ID'

before_script:
  - mkdir -p "$HERO_INSTALL"
  - mkdir -p "$TEMP_JOB_DIR"

after_script:
  - chmod -R u+w "$HERO_INSTALL"
  - chmod -R u+w "$TEMP_JOB_DIR"
  - rm -rf "$TEMP_JOB_DIR"

stages:
  - build_test_rest

build_test_archive:
  stage: build_test_rest
  script:
    - ./pack_huawei.sh
    - cd "$TEMP_JOB_DIR"
    - cp "$CI_PROJECT_DIR/hero_huawei.tar.gz" .
    - tar xf hero_huawei.tar.gz && rm hero_huawei.tar.gz
    - export HERO_INSTALL="$(pwd)/install"
    ### build base toolchains
    - make tc-pulp
    ### build RTL tests
    - source env/ehuawei-test.sh
    ### Test both simulators
    - >
      for sim in vsim vcs; do
        # Compile testbench
        cd hardware/$sim
        ./compile.sh
        for d in hello parMatrixMul; do
          make -C ../../example-apps/$d clean all
          ../test/gen_slm_files.sh $d
          ./start_sim.sh
        done
        cd -
      done
    ### build SDK and software tests
    - make sdk-pulp
    - source env/esim.sh
    ### Test both simulators
    - >
      for sim in vsim vcs; do
        # Compile testbench
        cd hardware/$sim
        ./compile.sh
        for d in tests-pulp; do
          make -C ../../example-apps/$d clean all
          ../test/gen_slm_files.sh $d
          ./start_sim.sh
        done
        cd -
      done

build_test_pulp-runtime:
  stage: build_test_rest
  script:
    ### build base toolchains
    - make tc-pulp
    ### Configure pulp-runtime
    - source env/ehuawei-test.sh
    ### Test both simulators
    - make -C "$CI_PROJECT_DIR/hardware" vcs/compile.sh
    - >
      for sim in vsim vcs; do
        # Compile testbench
        cd hardware/$sim
        ./compile.sh
        for d in hello parMatrixMul; do
          make -C ../../example-apps/$d clean all
          ../test/gen_slm_files.sh $d
          ./start_sim.sh
        done
        cd -
      done
  artifacts:
    paths:
      - install
      - example-apps
      - pulp

build_test_sdk:
  stage: build_test_rest
  script:
    ### build base toolchains
    - make tc-pulp
    ### build accelerator sdk
    - make sdk-pulp
    ### Configure for SDK
    - source env/esim.sh
    ### Test both simulators
    - make -C "$CI_PROJECT_DIR/hardware" vcs/compile.sh
    - >
      for sim in vsim vcs; do
        # Compile testbench
        cd hardware/$sim
        ./compile.sh
        for d in tests-pulp; do
          make -C ../../example-apps/$d clean all
          ../test/gen_slm_files.sh $d
          ./start_sim.sh
        done
        cd -
      done
  artifacts:
    paths:
      - install
      - example-apps
      - pulp

pulp_run_target_test:
  stage: build_test_rest
  script:
    ### setup toolchain
    - ./setup.sh
    - source env/ehuawei-test.sh
    ### compile testbench
    - cd hardware/vsim
    - ./compile.sh
    - cd -
    ### simulate examples
    - make -C example-apps/hello all run
    - cd -
  artifacts:
    paths:
      - example-apps
