variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'

before_script:
  - env
  - mkdir -p $HERO_INSTALL

after_script:
  - chmod -R u+w $HERO_INSTALL

stages:
  - build_fpga
  - build_toolchain
  - build_sdks
  - build_hetero
  - build_environ # TODO
  - test_xilzcu102

build_fpga:
  stage: build_fpga
  rules:
    - changes:
      - hardware/deps/**/*
      - hardware/fpga/**/*
      - hardware/src/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
      when: always
    - if: $CI_EVERYTHING
      when: always
  script: make -C hardware/fpga all

build_tc_pulp:
  stage: build_toolchain
  script: make tc-pulp
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output

build_tc_hrv-olinux:
  stage: build_toolchain
  script: make tc-hrv-olinux
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output

build_tc_har-olinux:
  stage: build_toolchain
  script: make tc-har-olinux
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output

build_sdk_pulp:
  stage: build_sdks
  script: make sdk-pulp
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output

build_sdk_hrv:
  stage: build_sdks
  script: make sdk-hrv
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output

build_sdk_har:
  stage: build_sdks
  script: make sdk-har
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output

build_hetero:
  stage: build_hetero
  script: make tc-llvm
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output

test_xilzcu102:
  stage: test_xilzcu102
  script:
    ### build examples
    - source env/exilzcu102.sh
    - >
      for d in helloworld; do
        make -C openmp-examples/$d all
      done
    ### test benchmarks
    - >
      for d in openmp-examples/polybench-acc/*/; do
        if [ $(basename $d) = "common" ]; then
          continue
        fi
        make -C $d only=pulp default-as=host clean all
        make -C $d only=pulp clean all
        .gitlab-ci.d/verify-bench.sh $(basename $d)
      done
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
      - output
