variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'
  RUST_LOG: 'memora=debug'

before_script:
  - env
  - mkdir -p $HERO_INSTALL

after_script:
  - chmod -R u+w $HERO_INSTALL

stages:
  - build1
  - build2
  - build3
  - build4
  - test

tc-pulp:
  stage: build1
  script:
    - >
      if ! memora lookup tc-pulp; then
        make tc-pulp
        chmod -R u+w $HERO_INSTALL
        memora insert tc-pulp
      fi

tc-har-olinux:
  stage: build1
  script:
    - >
      if ! memora lookup tc-har-olinux; then
        make tc-har-olinux
        chmod -R u+w $HERO_INSTALL
        memora insert tc-har-olinux
      fi

tc-hrv-olinux:
  stage: build1
  script:
    - >
      if ! memora lookup tc-hrv-olinux; then
        make tc-hrv-olinux
        chmod -R u+w $HERO_INSTALL
        memora insert tc-hrv-olinux
      fi

vsim-pulp:
  stage: build1
  script:
    - >
      if memora lookup vsim-pulp; then
        exit 0
      fi
    - cd hardware
    - make
    - cd vsim
    - ./compile.sh
    - memora insert vsim-pulp

sdk-pulp-and-sdk-har:
  stage: build2
  script:
    - >
      if memora lookup sdk-pulp-har-and-sdk-har; then
        exit 0
      fi
    - memora get tc-pulp
    - memora get tc-har-olinux
    - make sdk-pulp # TODO: `sdk-pulp-har` does not seem to work?
    - make sdk-har
    - memora insert sdk-pulp-har-and-sdk-har

sdk-pulp-and-sdk-hrv:
  stage: build2
  script:
    - >
      if memora lookup sdk-pulp-hrv-and-sdk-hrv; then
        exit 0
      fi
    - memora get tc-pulp
    - memora get tc-hrv-olinux
    - make sdk-pulp-hrv
    - make sdk-hrv
    - memora insert sdk-pulp-hrv-and-sdk-hrv

tc-llvm:
  stage: build3
  script:
    - >
      if memora lookup tc-llvm; then
        exit 0
      fi
    - memora get sdk-pulp-har-and-sdk-har
    - make tc-llvm
    - memora insert tc-llvm

bitstream-zcu102:
  stage: build3
  script:
    - >
      if ! memora lookup bitstream-zcu102; then
        cd hardware/fpga
        make hero_exilzcu102
        memora insert bitstream-zcu102
      fi

br-har-exilzcu102:
  stage: build4
  script:
    - >
      if memora lookup br-har-exilzcu102; then
        exit 0
      fi
    - memora get bitstream-zcu102
    - memora get tc-har-olinux
    - make br-har-exilzcu102
    - memora insert br-har-exilzcu102

br-hrv-ediggenesys2:
  stage: build4
  script:
    - >
      if memora lookup br-hrv-ediggenesys2; then
        exit 0
      fi
    - memora get tc-hrv-olinux
    - make br-hrv-ediggenesys2
    - memora insert br-hrv-ediggenesys2

br-hrv-eqemu:
  stage: build4
  script:
    - >
      if memora lookup br-hrv-eqemu; then
        exit 0
      fi
    - memora get tc-hrv-olinux
    - make br-hrv-eqemu
    - memora insert br-hrv-eqemu

test-zcu102-examples:
  stage: test
  script:
    - memora get tc-pulp
    - memora get tc-har-olinux
    - memora get sdk-pulp-and-sdk-har
    - make sdk-pulp # PULP SDK is not relocatable
    - source env/exilzcu102.sh
    ## build examples
    - >
      for d in helloworld mm-large mm-small; do
        make -C openmp-examples/$d all
      done
    ## test benchmarks: compile
    - >
      for d in openmp-examples/polybench-acc/*/; do
        if [ $(basename $d) = "common" ]; then
          continue
        fi
        make -C $d only=pulp default-as=host clean all
        make -C $d only=pulp clean all
        make -C $d default-as=host clean all
        make -C $d default-as=pulp clean all
      done
    ## test benchmarks: simulate
    - source env/esim-exilzcu102.sh
    - >
      for d in openmp-examples/polybench-acc/*/; do
        if [ $(basename $d) = "common" ]; then
          continue
        fi
        make -C $d only=pulp clean all
        .gitlab-ci.d/verify-bench.sh $(basename $d)
      done
