variables:
  GIT_DEPTH: 24
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'

before_script:
  - env
  - mkdir -p $HERO_INSTALL

after_script:
  - chmod -R u+w $HERO_INSTALL

stages:
  - build_har_olinux_exilzcu102
  - build_rest

build_har_olinux_exilzcu102:
  stage: build_har_olinux_exilzcu102
  script: 
    ### Bitstream
    bash -c ./.gitlab-ci.d/conditionally_build_bitstream.sh
    ### Toolchains
    - make har-exilzcu102
    ### build examples
    - source env/exilzcu102.sh
    - >
      for d in helloworld; do
        make -C openmp-examples/$d all
      done
    ### test benchmarks
    - >
      for d in openmp-examples/polybench-acc/*/; do
        if [ $(basename $d) = "common" ]; then
          continue
        fi
        make -C $d only=pulp default-as=host clean all
        make -C $d only=pulp clean all
        .gitlab-ci.d/verify-bench.sh $(basename $d)
      done
    ### Make SD card etc
    - make br-har-exilzcu102
  artifacts:
    paths:
    - install
    - openmp-examples
    - pulp/sdk
    - hardware/fpga/hero_exilzcu102/hero_exilzcu102.runs/impl_1/hero_exilzcu102_wrapper.bit
    - hardware/fpga/hero_exilzcu102/hero_exilzcu102.sdk/hero_exilzcu102_wrapper.hdf
    - local.cfg

build_other:
  stage: build_rest
  script: 
    ### Bitstream
    bash -c ./.gitlab-ci.d/conditionally_build_bitstream.sh
    ### Make everything that has not been tested as part of har-exilzcu102
    - make tc-hrv-olinux
    - make sdk-hrv
    - make br-har-ediggenesys2
    - make br-hrv-eqemu
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
