variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'

before_script:
  - env
  - mkdir -p $HERO_INSTALL

after_script:
  - chmod -R u+w $HERO_INSTALL

stages:
  - build_fpga
  - build_test_rest

build_fpga:
  stage: build_fpga
  rules:
    - changes:
      - hardware/deps/**/*
      - hardware/fpga/**/*
      - hardware/src/**/*
      when: always
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
      when: always
    - if: $CI_EVERYTHING
      when: always
  script: make -C hardware/fpga all

build_har_olinux_exilzcu102:
  stage: build_test_rest
  script: 
    ### Toolchains
    - make tc-pulp
    - make tc-har-olinux
    ### SDKs
    - env
    - ccache -C
    - env
    - make sdk-pulp
    - env
    - ccache -C
    - env
    - make sdk-har
    ### Hetero TC
    - make tc-llvm
    ### build examples
    - source env/exilzcu102.sh
    - >
      for d in helloworld; do
        make -C openmp-examples/$d all
      done
    ### test benchmarks
    - >
      for d in openmp-examples/polybench-acc/*/; do
        if [ $(basename $d) = "common" ]; then
          continue
        fi
        make -C $d only=pulp default-as=host clean all
        make -C $d only=pulp clean all
        .gitlab-ci.d/verify-bench.sh $(basename $d)
      done
    ### Make SD card etc
    - make br-har-exilzcu102
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk

build_other:
  stage: build_test_rest
  script: 
    ### Make everything that has not been tested as part of a complete setup
    - make tc-hrv-olinux
    - make sdk-hrv
    - make br-har-ediggenesys2
    - make br-hrv-eqemu
  artifacts:
    paths:
      - install
      - openmp-examples
      - pulp/sdk
