variables:
  GIT_DEPTH: 24
  GIT_SUBMODULE_STRATEGY: recursive
  HERO_INSTALL: '$CI_PROJECT_DIR/install'
  TEMP_JOB_DIR: '$CI_PROJECT_DIR/archive/hero_gitlab_ci_$CI_JOB_ID'

before_script:
  - env
  - mkdir -p $HERO_INSTALL
  - mkdir -p "$TEMP_JOB_DIR"

after_script:
  - chmod -R u+w $HERO_INSTALL
  - chmod -R u+w "$TEMP_JOB_DIR"
  - rm -rf "$TEMP_JOB_DIR"

stages:
  - build_test_archive
  - build_har_olinux_exilzcu102

build_test_archive:
  stage: build_test_archive
  script:
    - ./pack_siemens.sh
    - cd "$TEMP_JOB_DIR"
    - cp "$CI_PROJECT_DIR/hero_siemens.tar.gz" .
    - tar xf hero_siemens.tar.gz && rm hero_siemens.tar.gz
    - export HERO_INSTALL="$(pwd)/install"
    - mkdir -p "$HERO_INSTALL"
    #- ./setup.sh
  artifacts:
    paths:
      - hero_siemens.tar.gz

build_har_olinux_exilzcu102:
  stage: build_har_olinux_exilzcu102
  script:
    - true
    #### Bitstream
    #- bash -c ./.gitlab-ci.d/conditionally_build_bitstream.sh
    #### Toolchains
    #- make har-exilzcu102
    #### Simulator
    #- make -C hardware
    #- cd hardware/vsim
    #- ./compile.sh
    #- cd ../..
    #### test benchmarks: compile
    #- source env/exilzcu102.sh
    #- >
    #  for d in openmp-examples/polybench-acc/*/; do
    #    if [ $(basename $d) = "common" ]; then
    #      continue
    #    fi
    #    make -C $d only=pulp default-as=host clean all
    #    make -C $d only=pulp clean all
    #    make -C $d default-as=host clean all
    #    make -C $d default-as=pulp clean all
    #  done
    #### test benchmarks: simulate
    #- source env/esim-exilzcu102.sh
    #- >
    #  for d in openmp-examples/polybench-acc/*/; do
    #    if [ $(basename $d) = "common" ]; then
    #      continue
    #    fi
    #    make -C $d only=pulp clean all
    #    .gitlab-ci.d/verify-bench.sh $(basename $d)
    #  done
  artifacts:
    paths:
      #- install
      #- openmp-examples
      #- pulp/sdk
      #- hardware/fpga/hero_exilzcu102/hero_exilzcu102.runs/impl_1/hero_exilzcu102_wrapper.bit
      #- hardware/fpga/hero_exilzcu102/hero_exilzcu102.sdk/hero_exilzcu102_wrapper.hdf
      #- local.cfg
